update output to include external IP
Signed-off-by: Jeremy J. Miller <jeremymv2@users.noreply.github.com>

diff --git a/tests/e2e/04-loadbalancer-svc.yaml b/tests/e2e/04-loadbalancer-svc.yaml
--- a/tests/e2e/04-loadbalancer-svc.yaml
+++ b/tests/e2e/04-loadbalancer-svc.yaml
@@ -12,7 +12,7 @@ commands:
   - script: |
       LB_IP=$(kubectl get svc nginx-kuttl -o jsonpath="{.status.loadBalancer.ingress[0].ip}" || exit)
       echo "$LB_IP" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" || {
-        echo 'ERROR: LoadBalancer service has no IP set!'; exit 1
+        echo 'ERROR: LoadBalancer service has no external IP set!'; exit 1
       }
 delete:
   - apiVersion: apps/v1
